language: node_js
matrix:
  include:
    - node_js: lts/*
      script:
        - npm run lint
        - npm test
        - npm run coverage
    - node_js: 14
      script:
        - npm run lint
        - npm test
        - npm run coverage
    - node_js: 13
      script:
        - npm run lint
        - npm test
        - npm run coverage
    - node_js: 12
      script:
        - npm run lint
        - npm test
        - npm run coverage
    - node_js: 11
      script:
        - npm run lint
        - npm test
        - npm run coverage
    - node_js: 10
      script:
        - npm run lint
        - npm test
        - npm run coverage
    - language: minimal
      services:
        - docker
      script:
        - docker build -f Dockerfile.deno -t urlcat-deno .
        - docker run --rm urlcat-deno run ./src/index.ts
        - docker run --rm urlcat-deno bundle ./src/index.ts
        - docker run --rm urlcat-deno lint --unstable src/
        - docker rmi urlcat-deno